In [13]:
import numpy as np
#create 0s
z=np.zeros(10)
z[4] = 1
print(z)
#create an array
zz = np.arange(10,50, 1)#start, stop, stepsize
print(zz)
#linespace and logspace
#linespace includes both ends
np.linspace(0,10,25)
np.logspace(0,10,10, base = np.e)
#random data
np.random.rand(5,5)#create a 5*5 matrix with value of runif(0,1) 
np.random.randn(5,5)#std normal distributed r.n
np.random.randint(0,9,5) #(low, high, size)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


array([[ 0.78209862,  0.52730302,  0.40264765,  0.05718696,  0.98196807],
       [ 0.48239506,  0.53965532,  0.02885746,  0.87167016,  0.32083394],
       [ 0.9666628 ,  0.85279624,  0.51987126,  0.99166827,  0.03438247],
       [ 0.71477723,  0.25273313,  0.73714288,  0.27303776,  0.66379265],
       [ 0.30076944,  0.13757   ,  0.60774446,  0.78691123,  0.77791652]])

In [125]:
#倒置向量
zz = np.arange(50)
zz = zz[::-1]
#print(zz)
aq = np.arange(10)
print(aq, aq[::-1],aq[::-2])#  a::b means select all from a to b in aq
#-x, means go reversed order, return value with stop x
#print(aq[::])
print(aq.reverse())

[0 1 2 3 4 5 6 7 8 9] [9 8 7 6 5 4 3 2 1 0] [9 7 5 3 1]


AttributeError: 'numpy.ndarray' object has no attribute 'reverse'

In [16]:
#create a matrix
z = np.arange(9).reshape(3,3)
print(z)
#create identity matrix
print(np.eye(3))
#create a 3x3 array
print(np.random.random((3,3,3)))
#create a 10*10 array, then find the max, min
a = np.random.random((10,10))

amax, amin = a.max(), a.min()
print(a, amax, amin)
#get a average of a vector
print(np.random.random(30).mean())


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[[ 0.50304659  0.03832627  0.32024376]
  [ 0.5802379   0.82570527  0.24306212]
  [ 0.89963722  0.35983086  0.16766395]]

 [[ 0.78556548  0.16484092  0.92295365]
  [ 0.36989528  0.11662701  0.36390457]
  [ 0.61271505  0.04227967  0.21838208]]

 [[ 0.37210932  0.35415185  0.2830128 ]
  [ 0.19132273  0.34799732  0.70729147]
  [ 0.35359355  0.08970289  0.42156799]]]
[[ 0.49484134  0.5616933   0.46187726  0.76706939  0.18174697  0.87870811
   0.3549003   0.10353001  0.197893    0.72305144]
 [ 0.17303793  0.56958792  0.20084183  0.52007805  0.57508104  0.81783779
   0.36852946  0.39320536  0.37037307  0.29827591]
 [ 0.16222439  0.4515099   0.87455419  0.95403778  0.13481738  0.01260621
   0.49260072  0.6494062   0.25811171  0.54619828]
 [ 0.0069445   0.50871473  0.5731248   0.14892834  0.20130689  0.69905703
   0.4340969   0.84980618  0.99713504  0.09033684]
 [ 0.66193654  0.52467936  0.55778552  0.1812362   0.9023602

In [64]:
#create a diagonal matrix 5*5
np.diag([1,2,3])
print(np.diag([1,2,3], k = -1))
print(np.diag(1+np.arange(4), k=-2))
print(A,np.diag(A), np.diag(A,-1))

[[0 0 0 0]
 [1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]] [ 0 11 22 33 44] [10 21 32 43]


In [18]:
#find non-zero 
print(np.nonzero([1,2,0,0,4,5,0]))
#create a 10*10 array, with boundary 1, inner 0
b = np.ones((10,10))
b[1:-1,1:-1] = 0
print(b)

(array([0, 1, 4, 5], dtype=int64),)
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [19]:
print(0*np.nan, np.nan == np.nan, np.inf>np.nan, np.nan-np.nan, 0.3 ==3*0.1)

nan False False nan False


In [36]:
#Manipulating arrays
#get index
v = np.array([[1,2],[3,4]])

print(v[1,0], v[1],v[1,:],v.shape)
v[0,1] =4
print(v)
#index slicing A[lower: upper:stepsize]
A = np.array([[ 0,  1,  2,  3,  4],
              [10, 11, 12, 13, 14],
              [20, 21, 22, 23, 24],
              [30, 31, 32, 33, 34],
              [40, 41, 42, 43, 44]])
print(A[1:2:2])
print(A[::], A[:: -2])#lower :upper, stepsize all take the default values, 
#reversed order step = 2
print(A[-2:])#last 2 elements
print(A[1:3, 1:3])
print(A[::2,::2])

3 [3 4] [3 4] (2, 2)
[[1 4]
 [3 4]]
[[10 11 12 13 14]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]] [[40 41 42 43 44]
 [20 21 22 23 24]
 [ 0  1  2  3  4]]
[[30 31 32 33 34]
 [40 41 42 43 44]]
[[11 12]
 [21 22]]
[[ 0  2  4]
 [20 22 24]
 [40 42 44]]


In [53]:
#index array
row_index, col_index = [1,2,3], [1,2,-1]
print(np.shape(row_index))
print(A[row_index, col_index])
#Boolean/mask

row_mask, col_mask = [False, True,True , True, False], [False, True, True,False,True]
print(A[row_mask, col_mask])
print(A[np.array([0,1,1,1,0], dtype = bool), np.array([0,1,1,0,1], dtype = bool)])
#usefull
B = np.arange(0,20,0.5)
mask = (5<B)*(B<10)
print(B[(B <10)*(B>5)])

(3,)
[11 22 34]
[11 22 34]
[11 22 34]
[ 5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5]


In [27]:
#consider a array with (6*7*8), what is the index of 100th (x,y,z)
print(np.unravel_index(100, (6,7,8)))
#create a 8*8 matrix like chast
d = np.zeros((8,8), dtype = int)
d[1::2, ::2] = 1
d[::2, 1::2] = 1
print(d)
print(d[2::3])

(1, 5, 4)
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [30]:
#normalize a matrix
print(a, amax, amin)
a = (a-amin)/(amax-amin)
print(a)

[[ 0.49484134  0.5616933   0.46187726  0.76706939  0.18174697  0.87870811
   0.3549003   0.10353001  0.197893    0.72305144]
 [ 0.17303793  0.56958792  0.20084183  0.52007805  0.57508104  0.81783779
   0.36852946  0.39320536  0.37037307  0.29827591]
 [ 0.16222439  0.4515099   0.87455419  0.95403778  0.13481738  0.01260621
   0.49260072  0.6494062   0.25811171  0.54619828]
 [ 0.0069445   0.50871473  0.5731248   0.14892834  0.20130689  0.69905703
   0.4340969   0.84980618  0.99713504  0.09033684]
 [ 0.66193654  0.52467936  0.55778552  0.1812362   0.90236021  0.17649143
   0.65246763  0.93199724  0.03790795  0.22094879]
 [ 0.82342691  0.63059642  0.50264869  0.97563813  0.9944031   0.99105562
   0.30614048  0.28989946  0.40609785  0.50303041]
 [ 0.36106899  0.78817925  0.66428286  0.59540087  0.01609993  0.47222494
   0.71816039  0.22787362  0.45506454  0.0097727 ]
 [ 0.82413808  0.74873476  0.80225448  0.66786756  0.41241221  0.63347977
   0.93626271  0.2967471   0.21202991  0.30743036]


In [34]:
#multiply matrix
print(np.ones((5,3)), np.ones((3,2)), np.dot(np.ones((5,3)), np.ones((3,2))))


[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]] [[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]] [[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


In [36]:
# take the negative value
d = np.arange(11)
d[(d>3)&(d<=8)] *=-1
print(d)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [45]:
#create a length = 10 vector with in (0,1)
print(np.linspace(0,1,12, endpoint = True)[1:-1])
#sort a vector
f = np.random.random(10)
print(f.sort())

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]
None


In [9]:
#numpy array
print(np.array([1,2,3,4]))
print(np.array([[1,2],[3,4]]))
print(type(np.array([1,2,3,4])))

print(np.shape(np.array([1,2,3,4])))
print(np.shape(np.array([[1,2],[3,4]])))

print(np.array([1,2,3,4], dtype = float))
print(np.array([[1,2], [3,4]], dtype = int))

M1 = np.array([[1.,2.], [3., 4.]])
print(M1.dtype)
M2 = M1.astype(int)
print(M2.dtype)

[1 2 3 4]
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
(4,)
(2, 2)
[ 1.  2.  3.  4.]
[[1 2]
 [3 4]]
float64
int32


In [60]:
#functions for extracting data from arrays and creating arrays
#where
mask
indice = np.where(mask)
print(mask, indice, B[indice])
#take
B2 = np.arange(-3,3)
print(np.take(B2, row_index), B2[row_index], B2.take(row_index))

[False False False False False False False False False False False  True
  True  True  True  True  True  True  True  True False False False False
 False False False False False False False False False False False False
 False False False False] (array([11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64),) [ 5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5]
[-2 -1  0] [-2 -1  0] [-2 -1  0]


In [81]:
#matrix algebra
np.dot(A,A)
np.shape(A)
b = np.arange(3,8)
print(A,b, np.dot(A,A), np.dot(A,b), np.dot(b,b))
M = np.matrix(A)
v = np.matrix(b).T # transverse from row to col
print(M.shape, v.shape)
print(A*A, A*b, b.T*b)


[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]] [3 4 5 6 7] [[ 300  310  320  330  340]
 [1300 1360 1420 1480 1540]
 [2300 2410 2520 2630 2740]
 [3300 3460 3620 3780 3940]
 [4300 4510 4720 4930 5140]] [  60  310  560  810 1060] 135
(5, 5) (5, 1)
[[   0    1    4    9   16]
 [ 100  121  144  169  196]
 [ 400  441  484  529  576]
 [ 900  961 1024 1089 1156]
 [1600 1681 1764 1849 1936]] [[  0   4  10  18  28]
 [ 30  44  60  78  98]
 [ 60  84 110 138 168]
 [ 90 124 160 198 238]
 [120 164 210 258 308]] [ 9 16 25 36 49]


In [92]:
#data proecessing
data = np.random.RandomState(seed = 1).randint(1,30,30).reshape(5,6)
#from 1 to 30, random select 30, reshape set the number of row/col
print(data)
data.shape
#mean, std
print(np.mean(data[:, 3]), np.std(data[:,3]), np.var(data[:,3]), data[:,3].min(), data.max())
print(np.sum(data[:,3]), np.prod(data[:3]), np.cumprod(data[:3]+1))#cummulative sum
print(np.trace(A))
print(data.max(), data.max(axis =0), data.max(axis=1))#max in each row, max in each col

[[ 6 12 13  9 10 12]
 [ 6 16  1 17  2 13]
 [ 8 14 29  7 26 19]
 [21  6 19 21 12 29]
 [11 29 15 19  5 24]]
14.6 5.57135531087 31.04 7 29
73 1456340992 [          7          91        1274       12740      140140     1821820
    12752740   216796580   433593160  -785257712  1939194160  1378914464
  -474671712  1469858912  1146094400   578820608 -1551712768  -969484288]
110
29 [21 29 29 21 26 29] [13 17 29 29 29]


In [123]:
#reshape, resizing, stacking arrays
n,m = A.shape
B =A.reshape((1,n*m))#change 5*5 A into 1*25 B
B[0,0:5] = 5
print(B, A)
#Here, elements in A is also being changed once you change B

#also can use flatten()
C = A.flatten()
C[0:5] = 10
print(A, C)
#now A is not changed as C is changed, because C is a copy of A, not the original A
#stacking
x = np.array([1,2,4,6,8])
y = np.array([9,19,23,55,2])
z = np.column_stack([x,y]) #cbind
zz = np.row_stack([x,y])#rbind
print(z,zz)

[[ 5  5  5  5  5 10 11 12 13 14 20 21 22 23 24 30 31 32 33 34 40 41 42 43
  44]] [[ 5  5  5  5  5]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
[[ 5  5  5  5  5]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]] [10 10 10 10 10 10 11 12 13 14 20 21 22 23 24 30 31 32 33 34 40 41 42 43 44]
[[ 1  9]
 [ 2 19]
 [ 4 23]
 [ 6 55]
 [ 8  2]] [[ 1  2  4  6  8]
 [ 9 19 23 55  2]]


In [109]:
#add new rows
v = np.array([1,2,3])
print(v[:, np.newaxis].shape, v[np.newaxis,:].shape)
#add new col/ new row
#deep copy
#like B = A.reshape, change B will also chaneg A, use np.copy to avoid
P = np.array([[1,2,3], [4,5,6], [9,10,12]])
Q = np.copy(P)
Q[0,0] = 100
print(P,Q)

(3, 1) (1, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 9 10 12]] [[100   2   3]
 [  4   5   6]
 [  9  10  12]]


In [113]:
#iterate over array elements
p = np.array([1,2,3,4])
for element in p:
    print(element)
q = np.array([[1,2],[3,4]])
for row in q:
    print("row",row)
    for element in row:
        print(element)
#use enumerate to get both value and index 
for row_index, row in enumerate(q):
    print("row_index", row_index, "row", row)
    for col_index, element in enumerate(row):
        print("col_index", col_index, "element", element)
        #update matrix value
        q[row_index, col_index] = element**2
print(q)

1
2
3
4
row [1 2]
1
2
row [3 4]
3
4
row_index 0 row [1 2]
col_index 0 element 1
col_index 1 element 2
row_index 1 row [3 4]
col_index 0 element 3
col_index 1 element 4
[[ 1  4]
 [ 9 16]]


In [115]:
#SciPy-library of scientific algorithms for Python
import matplotlib.pyplot as plt
from IPython.display import Image
from scipy import *
import scipy.linalg as la

In [120]:
#special functions
from scipy.special import jn, yn, jn_zeros, yn_zeros
n= 0#order
x = 0.0
# Bessel function of first kind
print("J_%d(%f) = %f" % (n, x, jn(n, x)))

x = 1.0
# Bessel function of second kind
print("Y_%d(%f) = %f" % (n, x, yn(n, x)))
y = linspace(0,10,100)
fig, ax = plt.subplots()
for n in range(4):
    ax.plot(x, jn(n,x), label = r"$J_%d(x)$" % n)
ax.legend();


J_0(0.000000) = 1.000000
Y_0(1.000000) = 0.088257


In [121]:
#integration
from scipy.integrate import quad, dblquad, tplquad
def f(x):
    return x
x_lower, x_higher = 0, 1
val, abserr = quad(f, x_lower, x_upper)
print("integral value=", val, "absolute error =", abserr)

NameError: name 'x_upper' is not defined